<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>GymTracker.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Scrutor" Version="5.0.1" />
    <ProjectReference Include="..\GymTracker.Domain\GymTracker.Domain.csproj" />
  </ItemGroup>

</Project>
