<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>GymTracker.Api</RootNamespace>
    <UserSecretsId>a7d5960a-8d32-44d6-a693-c7c908b9b981</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GymTracker.Application\GymTracker.Application.csproj" />
    <ProjectReference Include="..\GymTracker.Infrastructure\GymTracker.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" Version="1.*" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.19" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

</Project>
