services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gymtracker-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "GymTracker_SaP4ss!"
    ports:
      - "14333:1433"
    volumes:
      - gymtracker_sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P GymTracker_SaP4ss! -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  gymtracker_sql_data:
