<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>GymTracker.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.Firestore" Version="4.*" />
    <PackageReference Include="Google.Cloud.Storage.V1" Version="4.*" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.*" />
    <PackageReference Include="Scrutor" Version="5.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GymTracker.Application\GymTracker.Application.csproj" />
    <ProjectReference Include="..\GymTracker.Domain\GymTracker.Domain.csproj" />
  </ItemGroup>

</Project>
